export const content = `
<h2 class="text-2xl font-bold mb-4 mt-8">25 Thoughtful Mother’s Day Gifts She Will Love</h2>
<p class="mb-6 text-zinc-700 dark:text-zinc-300">Finding the perfect gift means thinking of what makes your mum smile. We've gathered a wealth of ideas (far more than 25!) to spark your imagination – you know your mum best, so pick ones that match her style and passions:</p>
<ol class="list-decimal space-y-4 mb-6 text-zinc-700 dark:text-zinc-300 pl-6">
<li class="pl-2"><strong>Handwritten Letter or Poem:</strong> Never underestimate the power of words. Write down your gratitude, a favourite memory, or an "open when" letter bundle. This is free but priceless, and she'll keep it forever.</li>
<li class="pl-2"><strong>Family Photo Album or Frame:</strong> Collect candid family shots in a beautiful album, or frame a special photo of you with her. Each time she looks at it, she'll feel loved.</li>
<li class="pl-2"><strong>Personalized Jewelry:</strong> A necklace or bracelet engraved with her initials, birthstone or children's names. These always feel "just for her."</li>
<li class="pl-2"><strong>Homemade Treats:</strong> Bake her favourite cookies, jam, or bread. Present it in a pretty tin with a ribbon. It shows care and saves her from kitchen chores.</li>
<li class="pl-2"><strong>DIY Coupon Book:</strong> Create coupons she can redeem: “One home-cooked dinner,” “One free car wash,” “Movie night of your choice,” etc. It’s a fun promise of future treats.</li>
<li class="pl-2"><strong>Memory Journal:</strong> A blank diary or scrapbook where she can jot down thoughts or paste photos. You could start it by writing a first page for her.</li>
<li class="pl-2"><strong>Custom Home Decor:</strong> Perhaps a cushion or wall art with a meaningful quote, or a set of elegant candles or diffusers that suit her decor style.</li>
<li class="pl-2"><strong>Gardening Kit:</strong> If she loves plants, give her a set of beautiful planters, herb garden starter kit, or a birdhouse for the garden.</li>
<li class="pl-2"><strong>Cookbook of Family Recipes:</strong> Compile recipes of dishes she taught you in a neat book. It’s both practical and sentimental.</li>
<li class="pl-2"><strong>Experience Day:</strong> Whether it’s a spa day, a hot air balloon ride, or a craft workshop, plan a special outing. You could even do it together for quality time.</li>
<li class="pl-2"><strong>Subscription Box:</strong> There are boxes for everything – books, teas, cheeses, or self-care. Choose one that matches her interest; each monthly delivery will remind her of you.</li>
<li class="pl-2"><strong>Fitness or Hobby Gear:</strong> If she has a hobby (painting, yoga, hiking), get something to enhance it: a yoga bolster, painting set, or new hiking poles.</li>
<li class="pl-2"><strong>Tech Gift:</strong> An e-reader with some books loaded, or a digital photo frame pre-filled with family snapshots. Useful gadgets tailored to her tech comfort level can be exciting.</li>
<li class="pl-2"><strong>Wellness Kit:</strong> Assemble a “self-care” basket with a plush robe, slippers, herbal teas, and a journal or mindfulness coloring book. Encourage her to take time for herself.</li>
<li class="pl-2"><strong>Date Night Kit:</strong> Put together a “movie night” box: a new DVD or streaming gift card, popcorn, and cozy socks. It sets up a fun evening at home.</li>
<li class="pl-2"><strong>Coffee or Tea Set:</strong> A selection of premium coffees or teas, with a mug or French press, can brighten her mornings.</li>
<li class="pl-2"><strong>Donation in Her Name:</strong> If she’s the charitable type, donate to a cause she loves (with a card that explains). This thoughtful gesture shows you support her values.</li>
<li class="pl-2"><strong>Artwork:</strong> Commission a piece (portrait, pet painting, or abstract). Local artists or online services can create something one-of-a-kind that she’ll treasure.</li>
<li class="pl-2"><strong>Custom Puzzle:</strong> Turn a family photo into a jigsaw puzzle. It’s a unique, fun gift and an activity you can do together.</li>
<li class="pl-2"><strong>Plan a Picnic or Garden Tea Party:</strong> Assemble a picnic basket with homemade treats and a blanket. Spending time outside together can be the gift itself.</li>
<li class="pl-2"><strong>Flower Subscription:</strong> Instead of one bouquet, subscribe her to a monthly flower delivery. She’ll remember your kindness throughout the year.</li>
<li class="pl-2"><strong>Fancy PJ Set or Robe:</strong> A beautiful pair of pajamas or silk robe for ultimate comfort. Every morning when she puts it on, she’ll think of you.</li>
<li class="pl-2"><strong>Personal Care Gadgets:</strong> A quality face massager, electric toothbrush, or even a sound machine for better sleep can be surprising hits.</li>
<li class="pl-2"><strong>Local Experience:</strong> Tickets to a play, concert or local event you know she’d enjoy. Make a memory together.</li>
<li class="pl-2"><strong>Something She Mentioned:</strong> Often mums drop hints (“I love that scent” or “I wish I had time for [hobby]”). This year, really listen and get exactly what she subtly asked for – she’ll be amazed you were paying attention.</li>
</ol>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">Each of these ideas can be adapted to fit your budget and your mum’s personality. What makes any gift truly precious is the thought and love behind it – so wrap it in a loving card and a big hug.</p>
`;
