export const content = `
<h2 class="text-2xl font-bold mb-4 mt-8">Best Mother’s Day Gifts for New Mums</h2>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">Becoming a mother for the first time is a life-changing journey filled with joy and challenges. Your new mum may be exhausted from sleepless nights and constant care, so this Mother’s Day she deserves love and support more than ever. A thoughtful gift will show you see her strength and care for her well-being. Research shows that even simple gestures mean a lot – many mothers treasure a heartfelt card or something handmade. Quality time and rest also matter (32% of Brits plan to celebrate with family time), so consider treats that pamper her.</p>
<ol class="list-decimal space-y-4 pl-6 mb-6 text-zinc-700 dark:text-zinc-300">
<li class="pl-2"><strong>Comfort and Pampering:</strong> Give her a break with a spa set or bath kit, cozy robe or weighted blanket. Even booking a home massage or preparing her a special meal can feel like a big gift. New mums often have little “me-time,” so a relaxation voucher or luxurious bath bombs can say “you deserve rest.”</li>
<li class="pl-2"><strong>Keepsakes and Personal Touches:</strong> A personalized necklace with the baby’s initials, a custom photo album of her first weeks as a mum, or a handprint frame are treasures she’ll cherish. (Indeed, 28% of mums say they’d love something handmade.) A heartfelt letter from the baby (with a bit of imagination!) or a sentimental card can move her to tears of joy.</li>
<li class="pl-2"><strong>Practical Help:</strong> Consider a practical gift that lightens her load: a meal delivery subscription, a comfortable nursing pillow, or a newborn-care kit. Even something like organizing a cleaning service or offering baby-sitting time is a huge relief. Every new mum needs a helping hand, so showing you’ve thought of her needs will warm her heart.</li>
</ol>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">By focusing on her comfort and celebrating her new role, these gifts will let your new mum feel truly loved and appreciated.</p>
`;
