export const content = `
<h2 class="text-2xl font-bold mb-4 mt-8">Best Mother’s Day Gifts for Gardening Mums</h2>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">Gardening mums nurture life and beauty in their gardens just as they nurture their families. This Mother’s Day, gifts that celebrate nature will resonate with her love of plants. Every time she cultivates her flowers or herbs, she’ll remember the thought you put into her gift.</p>
<ul class="list-disc list-inside space-y-2 mb-6 text-zinc-700 dark:text-zinc-300">
<li><strong>Gardening Tools:</strong> Upgrade her toolkit with high-quality essentials. A durable garden kneeler and seat, ergonomic pruners, or a sturdy trowel set shows that you’re supporting her hobby. Personalized garden tools (for example, a trowel with her name) combine practicality with charm.</li>
<li><strong>Plants and Seeds:</strong> Give something living. A set of exotic seed packets for her favourite vegetables or flowers can inspire her next planting season. A beautiful potted indoor plant or a ready-to-go herb garden kit lets her bring the outdoors in. For added meaning, consider plants known for longevity (like lavender or bamboo) as a symbol of your lasting appreciation.</li>
<li><strong>Garden Décor:</strong> Help her garden look as lovely as she makes it. Decorative items like a solar garden light, a bird feeder, or a sundial can add personality. A garden statue or stepping stones engraved with a loving message adds sentimentality – every time she walks by, she’ll feel your love. (A note: 61% of UK shoppers now seek eco-friendly gifts, so choosing sustainable planters or organic seeds is extra thoughtful.)</li>
<li><strong>Gardening Gear:</strong> Treat her to things that make gardening more comfortable: a wide-brimmed sun hat, UV-protective gardening gloves in fun prints, or a breathable gardening apron with pockets. Even a simple gift like a stylish water bottle keeps her hydrated on hot days and shows you care about her comfort.</li>
</ul>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">By giving a gift that helps her grow her garden or enjoy it more, you honor the patience and care she pours into all aspects of her life. Your gift will bloom long after Mother’s Day is over.</p>
`;
