export const content = `
<h2 class="text-2xl font-bold mb-4 mt-8">Last-Minute Mother’s Day Gifts That Still Impress</h2>
<p class="mb-4 text-zinc-700 dark:text-zinc-300">Don’t panic if the calendar sneaked up on you – last-minute gifts can be just as heartfelt when chosen with care. In fact, 62% of UK shoppers buy Mother’s Day gifts online and rely on fast delivery. Same-day or next-day deliveries for flowers, chocolates or hampers mean you can still surprise her with something nice. The trick is creativity and a personal touch. Remember, your love isn’t measured by how early you shop, but by how sincerely you celebrate her.</p>
<ul class="list-disc list-inside space-y-2 mb-6 text-zinc-700 dark:text-zinc-300">
<li><strong>E-Gift Cards:</strong> Many retailers offer instant gift cards via email. Pick her favourite store, spa or even a meal delivery service, and send the e-card with a personal message. She’ll get it right away (and you can print a pretty note to accompany it).</li>
<li><strong>Express Delivery Treats:</strong> Order an online bouquet or hamper with same-day delivery if available. There are companies that deliver fresh flowers, gourmet cookies, or spa gift sets very quickly. Pair it with a hand-written card you give in person. (About 62% of Brits value fast delivery when shopping for Mother’s Day.)</li>
<li><strong>Digital Gifts:</strong> Send a heartfelt video or photo collage via email or social media. You could also buy her an e-book and email it. Another idea: create a digital coupon (a beautifully designed PDF) promising a homemade dinner or a back massage.</li>
<li><strong>Homemade Gesture:</strong> Sometimes a personal effort is best. Cook her favourite meal or bake a cake from scratch. Spend an evening doing her chores or pampering her (run a bath, do her nails, etc.). The element of surprise combined with genuine effort will impress her.</li>
<li><strong>Plan Ahead:</strong> Write her a meaningful letter or poem now, and promise an “experience” gift later (like booking a theatre show or a spa day). Present the letter on Mother’s Day so she has something special to open immediately, and reveal your plan verbally or on a pretty note.</li>
</ul>
<p class="mb-4 text-zinc-700 dark:text-zinc-300"><strong>Even last-minute, focus on her:</strong> a quick gift that suits her interests (a brief note about why you chose it) and your warm words will make her day. In the end, mother’s Day is about appreciation, not the clock.</p>
`;
